In [44]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from datetime import datetime, timedelta, time
import calendar

pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [45]:
pff = pd.read_csv('pff_pi.csv', index_col=0)
pff = pff.reset_index().drop(columns='index').reset_index().rename(columns={'index':'game_id'}).set_index('game_id')
pff = pff[['gamenum','Team', 'Opposing Team', 'Season', 'Week', 'Date', 'Time', 'H/A', 'W/L',
       'PA', 'PF', 'OVR', 'OFF', 'PASS', 'PBLK', 'RECV', 'RUN', 'RBLK', 'DEF',
       'RDEF', 'TACK', 'PRSH', 'COV', 'SPEC', 'OVR_opp', 'OFF_opp', 'PASS_opp',
       'PBLK_opp', 'RECV_opp', 'RUN_opp', 'RBLK_opp', 'DEF_opp', 'RDEF_opp',
       'TACK_opp', 'PRSH_opp', 'COV_opp', 'SPEC_opp']]
# pff.iloc[:,9:].drop(columns=['SPEC','SPEC_opp'])
pff.tail(2)

,gamenum,Team,Opposing Team,Season,Week,Date,Time,H/A,W/L,PA,PF,OVR,OFF,PASS,PBLK,RECV,RUN,RBLK,DEF,RDEF,TACK,PRSH,COV,SPEC,OVR_opp,OFF_opp,PASS_opp,PBLK_opp,RECV_opp,RUN_opp,RBLK_opp,DEF_opp,RDEF_opp,TACK_opp,PRSH_opp,COV_opp,SPEC_opp
game_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7166,3583,San Francisco 49Ers,Seattle Seahawks,2019,17,2019-12-29,8:20pm,A,W,21,26,79.9,88.9,88.3,81.6,84.6,72.2,69.2,64.7,65.6,66.5,58.7,65.5,56.3,60.3,70.3,67.1,76.2,67.5,58.9,68.1,39.7,37.0,26.6,61.1,42.6,66.9
7167,3583,Seattle Seahawks,San Francisco 49Ers,2019,17,2019-12-29,8:20pm,H,L,26,21,60.3,70.3,67.1,76.2,67.5,58.9,68.1,39.7,37.0,26.6,61.1,42.6,66.9,79.9,88.9,88.3,81.6,84.6,72.2,69.2,64.7,65.6,66.5,58.7,65.5,56.3

In [46]:
%timeit 
s = pff['Date']
pff['Date'] = pd.to_datetime(s, infer_datetime_format=True)

In [47]:
df = pff.copy()

In [48]:
df.iloc[:, 10:]

,PF,OVR,OFF,PASS,PBLK,RECV,RUN,RBLK,DEF,RDEF,TACK,PRSH,COV,SPEC,OVR_opp,OFF_opp,PASS_opp,PBLK_opp,RECV_opp,RUN_opp,RBLK_opp,DEF_opp,RDEF_opp,TACK_opp,PRSH_opp,COV_opp,SPEC_opp
game_id,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,17,65.5,64.7,50.3,65.6,69.1,57.0,65.8,64.4,69.9,67.8,80.2,44.8,-,74.2,68.3,65.5,45.2,73.5,60.6,64.1,77.0,68.6,59.9,73.2,72.0,-
1,28,74.2,68.3,65.5,45.2,73.5,60.6,64.1,77.0,68.6,59.9,73.2,72.0,-,65.5,64.7,50.3,65.6,69.1,57.0,65.8,64.4,69.9,67.8,80.2,44.8,-
2,20,78.9,65.6,47.5,63.1,63.9,61.1,73.0,89.8,67.4,78.9,76.3,89.9,-,60.7,60.5,40.3,74.0,64.3,62.1,72.0,60.7,68.8,68.6,66.0,51.6,-
3,6,60.7,60.5,40.3,74.0,64.3,62.1,72.0,60.7,68.8,68.6,66.0,51.6,-,78.9,65.6,47.5,63.1,63.9,61.1,73.0,89.8,67.4,78.9,76.3,89.9,-
4,19,68.4,66.9,58.6,86.2,72.0,50.4,66.0,67.4,81.6,61.8,59.4,57.8,-,66.3,60.9,57.2,68.7,60.7,58.8,57.0,70.5,71.8,71.9,53.2,68.0,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7163,31,70.8,72.9,67.5,75.5,76.9,63.9,54.0,61.5,86.1,71.9,60.6,53.3,64.8,66.0,67.9,69.0,76.2,67.8,60.9,48.2,59.6,69.8,61.6,59.6,51.6,62.8
7164,34,80.5,71.5,68.3,73.4,69.5,61.5,65.2,78.8,75.8,82.1,69.4,80.4,69.6,60.8,60.6,58.3,64.4,61.8,62.3,48.6,61.4,64.1,55.9,57.7,59.5,52.8
7165,17,60.8,60.6,58.3,64.4,61.8,62.3,48.6,61.4,64.1,55.9,57.7,59.5,52.8,80.5,71.5,68.3,73.4,69.5,61.5,65.2,78.8,75.8,82.1,69.4,80.4,69.6
7166,26,79.9,88.9,88.3,81.6,84.6,72.2,69.2,64.7,65.6,66.5,58.7,65.5,56.3,60.3,70.3,67.1,76.2,67.5,58.9,68.1,39.7,37.0,26.6,61.1,42.6,66.9
7167,21,60.3,70.3,67.1,76.2,67.5,58.9,68.1,39.7,37.0,26.6,61.1,42.6,66.9,79.9,88.9,88.3,81.6,84.6,72.2,69.2,64.7,65.6,66.5,58.7,65.5,56.3

Regression loop

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [50]:
df[df['Season']==2012]

,gamenum,Team,Opposing Team,Season,Week,Date,Time,H/A,W/L,PA,PF,OVR,OFF,PASS,PBLK,RECV,RUN,RBLK,DEF,RDEF,TACK,PRSH,COV,SPEC,OVR_opp,OFF_opp,PASS_opp,PBLK_opp,RECV_opp,RUN_opp,RBLK_opp,DEF_opp,RDEF_opp,TACK_opp,PRSH_opp,COV_opp,SPEC_opp
game_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3072,1536,Dallas Cowboys,New York Giants,2012,1,2012-09-05,8:30pm,A,W,17,24,72.1,75.2,84.9,64.1,77.9,68.0,61.5,62.9,74.4,57.9,72.0,50.9,-,64.8,68.9,83.0,49.4,68.1,50.9,61.1,57.9,70.1,89.0,64.5,44.6,-
3073,1536,New York Giants,Dallas Cowboys,2012,1,2012-09-05,8:30pm,H,L,24,17,64.8,68.9,83.0,49.4,68.1,50.9,61.1,57.9,70.1,89.0,64.5,44.6,-,72.1,75.2,84.9,64.1,77.9,68.0,61.5,62.9,74.4,57.9,72.0,50.9,-
3074,1537,Indianapolis Colts,Chicago Bears,2012,1,2012-09-09,1:00pm,A,L,41,21,58.0,69.6,48.8,67.5,66.3,69.4,90.2,43.2,41.7,47.2,58.2,42.9,-,79.4,85.2,72.0,68.6,75.8,72.0,87.9,64.4,31.7,72.2,71.5,69.6,-
3075,1537,Chicago Bears,Indianapolis Colts,2012,1,2012-09-09,1:00pm,H,W,21,41,79.4,85.2,72.0,68.6,75.8,72.0,87.9,64.4,31.7,72.2,71.5,69.6,-,58.0,69.6,48.8,67.5,66.3,69.4,90.2,43.2,41.7,47.2,58.2,42.9,-
3076,1538,Philadelphia Eagles,Cleveland Browns,2012,1,2012-09-09,1:00pm,A,W,16,17,78.3,63.1,43.0,55.0,69.7,59.5,75.7,91.4,76.5,65.3,86.7,91.9,-,67.6,43.8,34.6,45.5,49.7,48.3,59.7,87.7,60.7,73.7,78.8,90.2,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,1789,San Francisco 49Ers,Arizona Cardinals,2012,17,2012-12-30,4:25pm,H,W,13,27,83.7,82.0,91.7,69.8,80.3,55.8,70.3,77.2,64.4,55.5,54.5,86.1,-,62.0,61.0,49.6,72.0,61.3,66.5,63.6,62.5,69.6,68.8,60.4,54.0,-
3580,1790,Los Angeles Rams,Seattle Seahawks,2012,17,2012-12-30,4:25pm,A,L,20,13,61.6,72.6,68.5,84.1,70.1,66.9,63.9,44.5,51.0,29.6,64.6,41.7,-,76.7,80.5,88.9,70.0,80.0,56.7,76.5,66.5,72.7,73.5,56.8,66.2,-
3581,1790,Seattle Seahawks,Los Angeles Rams,2012,17,2012-12-30,4:25pm,H,W,13,20,76.7,80.5,88.9,70.0,80.0,56.7,76.5,66.5,72.7,73.5,56.8,66.2,-,61.6,72.6,68.5,84.1,70.1,66.9,63.9,44.5,51.0,29.6,64.6,41.7,-
3582,1791,Dallas Cowboys,Washington Redskins,2012,17,2012-12-30,8:20pm,A,L,28,18,61.8,74.0,50.3,77.0,70.2,80.5,74.3,42.9,29.5,55.5,60.9,65.5,-,74.5,75.5,53.2,74.2,62.5,80.7,76.0,68.1,49.5,74.9,57.9,79.6,-
3583,1791,Washington Redskins,Dallas Cowboys,2012,17,2012-12-30,8:20pm,H,W,18,28,74.5,75.5,53.2,74.2,62.5,80.7,76.0,68.1,49.5,74.9,57.9,79.6,-,61.8,74.0,50.3,77.0,70.2,80.5,74.3,42.9,29.5,55.5,60.9,65.5,-

In [64]:
%%time
# initialize lists to store predictions
test_score_predictions = []
holdout_score_predictions = []
test_game_ids = []
holdout_game_ids = []

# start at 2012 season
current_date = datetime(2012,9,1)
stop_date = datetime(2020,1,1)

# loop through month
while current_date < stop_date:
    if current_date.month == 1:
        current_date = datetime(add_month.year, 9, 1)
    else:
        current_date = current_date
    print(current_date)
    
    month_ending = calendar.monthrange(current_date.year,current_date.month)
    month_ending_dt = datetime(current_date.year, current_date.month, month_ending[1])
    
    # create train/test and holdout dataframes dataframes
    prediction_df = df[df['Date']<current_date].iloc[:,10:].drop(columns=['SPEC','SPEC_opp']).tail(1280)
    holdout_df = df[(df['Date']<=month_ending_dt)&(df['Date']>=current_date)].iloc[:,10:].drop(columns=['SPEC','SPEC_opp'])
    
    # split y, X arrays
    y = prediction_df.iloc[:,0]
    X = prediction_df.iloc[:,1:]

    # train/test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False, random_state=42)

    # append game_ids from y_test
    test_game_ids.append(y_test.index.values)

    # train model - add cross validate later
    reg = LinearRegression().fit(X_train, y_train)

    # predict on test set
    test_preds = reg.predict(X_test)
    # append test_preds
    test_score_predictions.append(test_preds)

    # grab actual scores from the holdout set
    actual_scores = holdout_df.iloc[:,0]
    # get holdout X dataframe
    X_holdout = holdout_df.iloc[:,1:]

    # predict on holdout set
    holdout_preds = reg.predict(X_holdout)
    # append holdout predictions
    holdout_score_predictions.append(holdout_preds)
    
    # append game_ids from holdout set
    holdout_game_ids.append(holdout_df.index.values)
    
    days_in_month = calendar.monthrange(current_date.year, current_date.month)[1]
    add_month = current_date + timedelta(days = days_in_month)
    
    current_date = datetime(add_month.year, add_month.month, 1)

2012-09-01 00:00:00
2012-10-01 00:00:00
2012-11-01 00:00:00
2012-12-01 00:00:00
2013-09-01 00:00:00
2013-10-01 00:00:00
2013-11-01 00:00:00
2013-12-01 00:00:00
2014-09-01 00:00:00
2014-10-01 00:00:00
2014-11-01 00:00:00
2014-12-01 00:00:00
2015-09-01 00:00:00
2015-10-01 00:00:00
2015-11-01 00:00:00
2015-12-01 00:00:00
2016-09-01 00:00:00
2016-10-01 00:00:00
2016-11-01 00:00:00
2016-12-01 00:00:00
2017-09-01 00:00:00
2017-10-01 00:00:00
2017-11-01 00:00:00
2017-12-01 00:00:00
2018-09-01 00:00:00
2018-10-01 00:00:00
2018-11-01 00:00:00
2018-12-01 00:00:00
2019-09-01 00:00:00
2019-10-01 00:00:00
2019-11-01 00:00:00
2019-12-01 00:00:00
Wall time: 466 ms

In [66]:
# flatten list of lists
flat_holdout_score_predictions = [item for sublist in holdout_score_predictions for item in sublist]
flat_holdout_game_ids = [item for sublist in holdout_game_ids for item in sublist]

results = pd.DataFrame(data=flat_holdout_score_predictions, index=flat_holdout_game_ids, columns=['predicted_score'])
results_merge = results.merge(df, left_index=True, right_index=True)
results_merge.head(2)

,predicted_score,gamenum,Team,Opposing Team,Season,Week,Date,Time,H/A,W/L,PA,PF,OVR,OFF,PASS,PBLK,RECV,RUN,RBLK,DEF,RDEF,TACK,PRSH,COV,SPEC,OVR_opp,OFF_opp,PASS_opp,PBLK_opp,RECV_opp,RUN_opp,RBLK_opp,DEF_opp,RDEF_opp,TACK_opp,PRSH_opp,COV_opp,SPEC_opp
3072,29.265023,1536,Dallas Cowboys,New York Giants,2012,1,2012-09-05,8:30pm,A,W,17,24,72.1,75.2,84.9,64.1,77.9,68.0,61.5,62.9,74.4,57.9,72.0,50.9,-,64.8,68.9,83.0,49.4,68.1,50.9,61.1,57.9,70.1,89.0,64.5,44.6,-
3073,23.997504,1536,New York Giants,Dallas Cowboys,2012,1,2012-09-05,8:30pm,H,L,24,17,64.8,68.9,83.0,49.4,68.1,50.9,61.1,57.9,70.1,89.0,64.5,44.6,-,72.1,75.2,84.9,64.1,77.9,68.0,61.5,62.9,74.4,57.9,72.0,50.9,-

In [67]:
from sklearn.metrics import mean_squared_error
math.sqrt(mean_squared_error(results_merge['predicted_score'].values, results_merge['PF'].values))

6.9864712234077775